
x=float(input("x "))
y=float(input("y "))
x1=float(input("x1 "))
y1=float(input("y1 "))
x2=float(input("x2 "))
y2=float(input("y2 "))
storona1=float(x1-x)+(y1-y)
storona2=float(x2-x1)+(y2-y1)
storona3=float(x2-x)+(y2-y)
print(storona1+storona2+storona3)